services:
  rabbitmq:
    image: rabbitmq:3.11.15-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit_user
      RABBITMQ_DEFAULT_PASS: rabbit_password
    volumes:
      - type: volume
        target: /var/lib/rabbitmq

